### ISSUE TITLE
Unable to build tpk after updating to 3.27.1

### ISSUE THREAD

**Issue by Alexjk7777** [flutter-tizen/flutter-tizen#639]
After updating flutter version to 3.27.1 flutter-tizen build was failing without any errors in jenkins , The only error log i was getting is as below
#36 265.8 /home/builder/.nuget/packages/tizen.net.sdk/1.1.9/build/Tizen.NET.Sdk.Packaging.targets(622,5): error TS0005: Error occurred during tpk signing. Please check certificate file & password [/home/builder/app/tizen/Runner.csproj]
#36 265.8 /home/builder/.nuget/packages/tizen.net.sdk/1.1.9/build/Tizen.NET.Sdk.Packaging.targets(622,5): error TS0005: message : PKCS12 key store MAC invalid - wrong password or corrupted file. [/home/builder/app/tizen/Runner.csproj]
#36 265.8 /home/builder/.nuget/packages/tizen.net.sdk/1.1.9/build/Tizen.NET.Sdk.Packaging.targets(622,5): error TS0005: file: /home/builder/SamsungUniversalCertificate/author.p12 [/home/builder/app/tizen/Runner.csproj]
#36 265.8     8 Warning(s)
#36 265.8     1 Error(s)

Using the same certificate i was able to build using 3.16.2 without any errors, also tried with newer author.p12 still it fails with same error. I have all the packages and cli installed why this might be happening

~/Applications/tizen-studio/package-manager$ ./package-manager-cli.bin show-pkgs
Display installed packages' information
Package Manager (0.5.61)

Status	Package Name                            	Package Version	Component Name      
------------------------------------------------------------------------------------------------------------------------
ni   	TIZEN-9.0                               	0.0.27         	9.0 Tizen           
ni   	TIZEN-9.0-Emulator                      	0.0.27         	Emulator            
ni   	TIZEN-9.0-NativeAppDevelopment          	0.0.27         	Native app. development (IDE)
ni   	TIZEN-9.0-WebAppDevelopment             	0.0.27         	Web app. development (IDE)
ni   	AdvancedTIZEN-9.0                       	0.0.0          	Advanced            
ni   	TIZEN-9.0-NativeAppDevelopment-CLI      	0.0.27         	Native app. development (CLI)
ni   	TIZEN-9.0-WebFramework-TAU-CLI          	0.0.27         	TAU (CLI)           
ni   	TIZEN-9.0-WebFramework-TAU              	0.0.27         	TAU (IDE)           
i    	TIZEN-9.0-WebAppDevelopment-CLI         	0.0.27         	Web app. development (CLI)
ni   	TIZEN-8.0                               	0.0.25         	8.0 Tizen           
ni   	TIZEN-8.0-Emulator                      	0.0.25         	Emulator            
ni   	TIZEN-8.0-NativeAppDevelopment          	0.0.25         	Native app. development (IDE)
ni   	TIZEN-8.0-WebAppDevelopment             	0.0.25         	Web app. development (IDE)
ni   	AdvancedTIZEN-8.0                       	0.0.0          	Advanced            
ni   	TIZEN-8.0-NativeAppDevelopment-CLI      	0.0.25         	Native app. development (CLI)
ni   	TIZEN-8.0-WebFramework-TAU-CLI          	0.0.25         	TAU (CLI)           
ni   	TIZEN-8.0-WebFramework-TAU              	0.0.25         	TAU (IDE)           
i    	TIZEN-8.0-WebAppDevelopment-CLI         	0.0.25         	Web app. development (CLI)
ni   	MOBILE-7.0                              	0.0.13         	7.0 Mobile          
ni   	MOBILE-7.0-Emulator                     	0.0.13         	Emulator            
ni   	MOBILE-7.0-NativeAppDevelopment         	0.0.13         	Native app. development (IDE)
ni   	MOBILE-7.0-WebAppDevelopment            	0.0.13         	Web app. development (IDE)
ni   	AdvancedMOBILE-7.0                      	0.0.0          	Advanced            
ni   	MOBILE-7.0-NativeAppDevelopment-CLI     	0.0.13         	Native app. development (CLI)
ni   	MOBILE-7.0-WebFramework-TAU-CLI         	0.0.13         	TAU (CLI)           
ni   	MOBILE-7.0-WebFramework-TAU             	0.0.13         	TAU (IDE)           
i    	MOBILE-7.0-WebAppDevelopment-CLI        	0.0.13         	Web app. development (CLI)
ni   	WEARABLE-7.0                            	0.0.13         	7.0 Wearable        
ni   	WEARABLE-7.0-Emulator                   	0.0.13         	Emulator            
ni   	WEARABLE-7.0-NativeAppDevelopment       	0.0.13         	Native app. development (IDE)
ni   	WEARABLE-7.0-WebAppDevelopment          	0.0.13         	Web app. development (IDE)
ni   	AdvancedWEARABLE-7.0                    	0.0.0          	Advanced            
ni   	WEARABLE-7.0-NativeAppDevelopment-CLI   	0.0.13         	Native app. development (CLI)
ni   	WEARABLE-7.0-WebFramework-TAU-CLI       	0.0.13         	TAU (CLI)           
ni   	WEARABLE-7.0-WebFramework-TAU           	0.0.13         	TAU (IDE)           
i    	WEARABLE-7.0-WebAppDevelopment-CLI      	0.0.13         	Web app. development (CLI)
ni   	MOBILE-6.5                              	0.0.9          	6.5 Mobile          
ni   	MOBILE-6.5-Emulator                     	0.0.9          	Emulator            
ni   	MOBILE-6.5-NativeAppDevelopment         	0.0.9          	Native app. development (IDE)
ni   	MOBILE-6.5-WebAppDevelopment            	0.0.9          	Web app. development (IDE)
ni   	AdvancedMOBILE-6.5                      	0.0.0          	Advanced            
ni   	MOBILE-6.5-NativeAppDevelopment-CLI     	0.0.9          	Native app. development (CLI)
ni   	MOBILE-6.5-WebFramework-TAU-CLI         	0.0.9          	TAU (CLI)           
ni   	MOBILE-6.5-WebFramework-TAU             	0.0.9          	TAU (IDE)           
i    	MOBILE-6.5-WebAppDevelopment-CLI        	0.0.9          	Web app. development (CLI)
ni   	WEARABLE-6.5                            	0.0.9          	6.5 Wearable        
ni   	WEARABLE-6.5-Emulator                   	0.0.9          	Emulator            
ni   	WEARABLE-6.5-NativeAppDevelopment       	0.0.9          	Native app. development (IDE)
ni   	WEARABLE-6.5-WebAppDevelopment          	0.0.9          	Web app. development (IDE)
ni   	AdvancedWEARABLE-6.5                    	0.0.0          	Advanced            
ni   	WEARABLE-6.5-NativeAppDevelopment-CLI   	0.0.9          	Native app. development (CLI)
ni   	WEARABLE-6.5-WebFramework-TAU-CLI       	0.0.9          	TAU (CLI)           
ni   	WEARABLE-6.5-WebFramework-TAU           	0.0.9          	TAU (IDE)           
i    	WEARABLE-6.5-WebAppDevelopment-CLI      	0.0.9          	Web app. development (CLI)
ni   	MOBILE-6.0                              	0.0.9          	6.0 Mobile          
ni   	MOBILE-6.0-Emulator                     	0.0.9          	Emulator            
ni   	MOBILE-6.0-NativeAppDevelopment         	0.0.9          	Native app. development (IDE)
ni   	MOBILE-6.0-WebAppDevelopment            	0.0.9          	Web app. development (IDE)
ni   	AdvancedMOBILE-6.0                      	0.0.0          	Advanced            
ni   	MOBILE-6.0-NativeAppDevelopment-CLI     	0.0.9          	Native app. development (CLI)
ni   	MOBILE-6.0-WebFramework-TAU-CLI         	0.0.9          	TAU (CLI)           
ni   	MOBILE-6.0-WebFramework-TAU             	0.0.9          	TAU (IDE)           
i    	MOBILE-6.0-WebAppDevelopment-CLI        	0.0.9          	Web app. development (CLI)
ni   	WEARABLE-6.0                            	0.0.9          	6.0 Wearable        
ni   	WEARABLE-6.0-Emulator                   	0.0.9          	Emulator            
ni   	WEARABLE-6.0-NativeAppDevelopment       	0.0.9          	Native app. development (IDE)
ni   	WEARABLE-6.0-WebAppDevelopment          	0.0.9          	Web app. development (IDE)
ni   	AdvancedWEARABLE-6.0                    	0.0.0          	Advanced            
i    	WEARABLE-6.0-NativeAppDevelopment-CLI   	0.0.9          	Native app. development (CLI)
ni   	WEARABLE-6.0-WebFramework-TAU-CLI       	0.0.9          	TAU (CLI)           
ni   	WEARABLE-6.0-WebFramework-TAU           	0.0.9          	TAU (IDE)           
i    	WEARABLE-6.0-WebAppDevelopment-CLI      	0.0.9          	Web app. development (CLI)
ni   	TOOLS                                   	3.0.6          	Tizen SDK tools     
ni   	Baseline-SDK                            	3.0.6          	Baseline SDK        
ni   	DOTNET-CLI-EXT                          	3.0.6          	.NET CLI            
ni   	Certificate-Manager                     	3.0.6          	Certificate Manager
ni   	Emulator                                	3.0.6          	Emulator manager    
i    	NativeCLI                               	3.0.6          	Native CLI          
ni   	NativeIDE                               	3.0.6          	Native IDE          
ni   	NativeToolchain                         	3.0.6          	Native toolchain    
ni   	NativeToolchain-Gcc-4.6                 	3.0.6          	Gcc 4.6 toolchain   
ni   	NativeToolchain-Gcc-4.9                 	3.0.6          	Gcc 4.9 toolchain   
ni   	NativeToolchain-Gcc-6.2                 	3.0.6          	Gcc 6.2 toolchain   
i    	NativeToolchain-Gcc-9.2                 	3.0.6          	Gcc 9.2 toolchain   
ni   	PlatformIDE                             	3.0.6          	Platform IDE        
i    	WebCLI                                  	3.0.6          	Web CLI             
ni   	WebIDE                                  	3.0.6          	Web IDE             
ni   	EXTRAS                                  	0.0.0          	Extras              
ni   	TV-SAMSUNG-Public                       	9.0.0          	TV Extensions-9.0   
ni   	TV-SAMSUNG-Public-Emulator              	9.0.0          	Emulator            
ni   	TV-SAMSUNG-Public-WebAppDevelopment     	9.0.0          	Web app. development
ni   	IOT-Headed-4.0                          	0.0.15         	IOT-Headed-4.0      
ni   	IOT-Headed-4.0-NativeAppDevelopment     	0.0.15         	Native app. development (IDE)
ni   	AdvancedIOT-Headed-4.0                  	0.0.0          	Advanced            
ni   	IOT-Headed-4.0-NativeAppDevelopment-CLI 	0.0.15         	Native app. development (CLI)
ni   	IOT-Headed-5.0                          	0.0.15         	IOT-Headed-5.0      
ni   	IOT-Headed-5.0-NativeAppDevelopment     	0.0.15         	Native app. development (IDE)
ni   	AdvancedIOT-Headed-5.0                  	0.0.0          	Advanced            
ni   	IOT-Headed-5.0-NativeAppDevelopment-CLI 	0.0.15         	Native app. development (CLI)
ni   	IOT-Headed-5.5                          	0.0.15         	IOT-Headed-5.5      
ni   	IOT-Headed-5.5-NativeAppDevelopment     	0.0.15         	Native app. development (IDE)
ni   	AdvancedIOT-Headed-5.5                  	0.0.0          	Advanced            
ni   	IOT-Headed-5.5-NativeAppDevelopment-CLI 	0.0.15         	Native app. development (CLI)
ni   	IOT-Headed-6.0                          	0.0.15         	IOT-Headed-6.0      
ni   	IOT-Headed-6.0-NativeAppDevelopment     	0.0.15         	Native app. development (IDE)
ni   	AdvancedIOT-Headed-6.0                  	0.0.0          	Advanced            
ni   	IOT-Headed-6.0-NativeAppDevelopment-CLI 	0.0.15         	Native app. development (CLI)
ni   	IOT-Headed-6.5                          	0.0.16         	IOT-Headed-6.5      
ni   	IOT-Headed-6.5-NativeAppDevelopment     	0.0.16         	Native app. development (IDE)
ni   	AdvancedIOT-Headed-6.5                  	0.0.0          	Advanced            
ni   	IOT-Headed-6.5-NativeAppDevelopment-CLI 	0.0.16         	Native app. development (CLI)
ni   	IOT-Headed-7.0                          	0.0.17         	IOT-Headed-7.0      
ni   	IOT-Headed-7.0-NativeAppDevelopment     	0.0.17         	Native app. development (IDE)
ni   	AdvancedIOT-Headed-7.0                  	0.0.0          	Advanced            
ni   	IOT-Headed-7.0-NativeAppDevelopment-CLI 	0.0.17         	Native app. development (CLI)
ni   	IOT-Headless-4.0                        	0.0.15         	IOT-Headless-4.0    
ni   	IOT-Headless-4.0-NativeAppDevelopment   	0.0.15         	Native app. development (IDE)
ni   	AdvancedIOT-Headless-4.0                	0.0.0          	Advanced            
ni   	IOT-Headless-4.0-NativeAppDevelopment-CLI	0.0.15         	Native app. development (CLI)
ni   	IOT-Headless-5.0                        	0.0.15         	IOT-Headless-5.0    
ni   	IOT-Headless-5.0-NativeAppDevelopment   	0.0.15         	Native app. development (IDE)
ni   	AdvancedIOT-Headless-5.0                	0.0.0          	Advanced            
ni   	IOT-Headless-5.0-NativeAppDevelopment-CLI	0.0.15         	Native app. development (CLI)
ni   	IOT-Headless-5.5                        	0.0.15         	IOT-Headless-5.5    
ni   	IOT-Headless-5.5-NativeAppDevelopment   	0.0.15         	Native app. development (IDE)
ni   	AdvancedIOT-Headless-5.5                	0.0.0          	Advanced            
ni   	IOT-Headless-5.5-NativeAppDevelopment-CLI	0.0.15         	Native app. development (CLI)
ni   	IOT-Headless-6.0                        	0.0.15         	IOT-Headless-6.0    
ni   	IOT-Headless-6.0-NativeAppDevelopment   	0.0.15         	Native app. development (IDE)
ni   	AdvancedIOT-Headless-6.0                	0.0.0          	Advanced            
ni   	IOT-Headless-6.0-NativeAppDevelopment-CLI	0.0.15         	Native app. development (CLI)
ni   	IOT-Headless-6.5                        	0.0.16         	IOT-Headless-6.5    
ni   	IOT-Headless-6.5-NativeAppDevelopment   	0.0.16         	Native app. development (IDE)
ni   	AdvancedIOT-Headless-6.5                	0.0.0          	Advanced            
ni   	IOT-Headless-6.5-NativeAppDevelopment-CLI	0.0.16         	Native app. development (CLI)
ni   	IOT-Headless-7.0                        	0.0.17         	IOT-Headless-7.0    
ni   	IOT-Headless-7.0-NativeAppDevelopment   	0.0.17         	Native app. development (IDE)
ni   	AdvancedIOT-Headless-7.0                	0.0.0          	Advanced            
ni   	IOT-Headless-7.0-NativeAppDevelopment-CLI	0.0.17         	Native app. development (CLI)
ni   	cert-add-on                             	2.0.70         	Samsung Certificate Extension
ni   	TV-SAMSUNG-Extension-Tools              	9.0.0          	TV Extensions Tools
ni   	TV-SAMSUNG-Extension-Resources          	9.0.0          	Web app. tools

**Comment by JSUYA** [comment]
Hi
3.27.1 includes a patch to optimize packaging times.
https://github.com/flutter-tizen/flutter-tizen/releases/tag/3.27.1-tizen.1.0.0

I guess you can refer to these patch and comments.
https://github.com/flutter-tizen/plugins/pull/838
https://github.com/flutter-tizen/flutter-tizen/pull/595#discussion_r2005372666
https://developer.tizen.org/community/tip-tech/how-manage-certificates-and-package-applications-different-ubuntu-setups/

Install dbus-x11 gnome-keyring and call it like below.

```
dbus-run-session -- bash -c "
  echo tizen | gnome-keyring-daemon --unlock &&
  // Do something
"
```

ex)
```
dbus-run-session -- bash -c "
  echo tizen | gnome-keyring-daemon --unlock &&
    tizen certificate -a tizen -p tizen -f tizen
    tizen security-profiles add \
      -n tizen \
      -a $HOME/tizen-studio-data/keystore/author/tizen.p12 \
      -p tizen
"
```

**Comment by Alexjk7777** [comment]
Tried all the possible solutions still its failing with same error

builder@bbd1b8dc6b77:~/my_new_app$ flutter-tizen create --tizen-language csharp dotnet_app
Creating project dotnet_app...
Resolving dependencies in `dotnet_app`... 
Downloading packages... 
Got dependencies in `dotnet_app`.
Wrote 135 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider: https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ cd dotnet_app
  $ flutter run

Your application code is in dotnet_app/lib/main.dart.

builder@bbd1b8dc6b77:~/my_new_app$ cd dotnet_app
builder@bbd1b8dc6b77:~/my_new_app/dotnet_app$ dbus-run-session -- bash -c                         
          echo tizen | gnome-keyring-daemon --unlock &&
          flutter-tizen build tpk -pcommon --debug
bash: -c: option requires an argument
GNOME_KEYRING_CONTROL=/home/builder/.cache/keyring-CLKD92
SSH_AUTH_SOCK=/home/builder/.cache/keyring-CLKD92/ssh

The tizen profile is used for signing.
target: tizen_dotnet_tpk
exception:Error: Failed to build .NET application:
Signing using certificates:
	Author cert : /home/builder/tizen-studio-data/keystore/author/tizen.p12
	Distributor cert : /home/builder/tizen-studio/tools/certificate-generator/certificates/distributor/tizen-distributor-signer.p12
	Distributor2 cert : 
  Determining projects to restore...
  Restored /home/builder/my_new_app/dotnet_app/tizen/Runner.csproj (in 710 ms).
  1 of 2 projects are up-to-date for restore.
  Tizen.Flutter.Embedding -> /home/builder/Applications/flutter-tizen/embedding/csharp/Tizen.Flutter.Embedding/bin/Debug/tizen80/Tizen.Flutter.Embedding.dll
  Runner -> /home/builder/my_new_app/dotnet_app/tizen/bin/Debug/tizen80/Runner.dll
  Configuration : 
  Platform : 
  TargetFramework : 
  TizenTpkFiles : shared/res/ic_launcher.png
  TizenTpkFiles : tizen-manifest.xml
  TizenTpkFiles : flutter/ephemeral/lib/libflutter_engine.so
  TizenTpkFiles : flutter/ephemeral/lib/libflutter_tizen.so
  TizenTpkFiles : flutter/ephemeral/res/flutter_assets/.app.deps.json
  TizenTpkFiles : flutter/ephemeral/res/flutter_assets/AssetManifest.bin
  TizenTpkFiles : flutter/ephemeral/res/flutter_assets/AssetManifest.json
  TizenTpkFiles : flutter/ephemeral/res/flutter_assets/FontManifest.json
  TizenTpkFiles : flutter/ephemeral/res/flutter_assets/fonts/MaterialIcons-Regular.otf
  TizenTpkFiles : flutter/ephemeral/res/flutter_assets/isolate_snapshot_data
  TizenTpkFiles : flutter/ephemeral/res/flutter_assets/kernel_blob.bin
  TizenTpkFiles : flutter/ephemeral/res/flutter_assets/NOTICES.Z
  TizenTpkFiles : flutter/ephemeral/res/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
  TizenTpkFiles : flutter/ephemeral/res/flutter_assets/shaders/ink_sparkle.frag
  TizenTpkFiles : flutter/ephemeral/res/flutter_assets/vm_snapshot_data
  TizenTpkFiles : flutter/ephemeral/res/icudtl.dat
/home/builder/.nuget/packages/tizen.net.sdk/1.1.7/build/Tizen.NET.Sdk.Packaging.targets(622,5): error TS0005: Error occurred during tpk signing. Please check certificate file & password
[/home/builder/my_new_app/dotnet_app/tizen/Runner.csproj]
/home/builder/.nuget/packages/tizen.net.sdk/1.1.7/build/Tizen.NET.Sdk.Packaging.targets(622,5): error TS0005: message : PKCS12 key store MAC invalid - wrong password or corrupted file.
[/home/builder/my_new_app/dotnet_app/tizen/Runner.csproj]
/home/builder/.nuget/packages/tizen.net.sdk/1.1.7/build/Tizen.NET.Sdk.Packaging.targets(622,5): error TS0005: file: /home/builder/tizen-studio-data/keystore/author/tizen.p12
[/home/builder/my_new_app/dotnet_app/tizen/Runner.csproj]

Build FAILED.

/home/builder/.nuget/packages/tizen.net.sdk/1.1.7/build/Tizen.NET.Sdk.Packaging.targets(622,5): error TS0005: Error occurred during tpk signing. Please check certificate file & password
[/home/builder/my_new_app/dotnet_app/tizen/Runner.csproj]
/home/builder/.nuget/packages/tizen.net.sdk/1.1.7/build/Tizen.NET.Sdk.Packaging.targets(622,5): error TS0005: message : PKCS12 key store MAC invalid - wrong password or corrupted file.
[/home/builder/my_new_app/dotnet_app/tizen/Runner.csproj]
/home/builder/.nuget/packages/tizen.net.sdk/1.1.7/build/Tizen.NET.Sdk.Packaging.targets(622,5): error TS0005: file: /home/builder/tizen-studio-data/keystore/author/tizen.p12
[/home/builder/my_new_app/dotnet_app/tizen/Runner.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.78

tz: error: error occured when building with /home/builder/Applications/dotnet/dotnet
#0      throwToolExit (package:flutter_tools/src/base/common.dart:34:3)
#1      DotnetTpk.build (package:flutter_tizen/build_targets/package.dart:187:7)
<asynchronous suspension>
#2      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:876:9)
<asynchronous suspension>
#3      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:637:16)
<asynchronous suspension>
#4      TizenBuilder.buildTpk (package:flutter_tizen/tizen_builder.dart:101:34)
<asynchronous suspension>
#5      BuildTpkCommand.runCommand (package:flutter_tizen/commands/build.dart:83:5)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1558:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:496:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:431:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:98:11)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
<asynchronous suspension>
#14     main (package:flutter_tizen/executable.dart:87:3)
<asynchronous suspension>


Building a Tizen application in debug mode...                      22.7s
The build failed.

**Comment by JSUYA** [comment]
> builder@bbd1b8dc6b77:/my_new_app/dotnet_app$ dbus-run-session -- bash -c
echo tizen | gnome-keyring-daemon --unlock &&
flutter-tizen build tpk -pcommon --debug
bash: -c: option requires an argument
GNOME_KEYRING_CONTROL=/home/builder/.cache/keyring-CLKD92
SSH_AUTH_SOCK=/home/builder/.cache/keyring-CLKD92/ssh

https://developer.tizen.org/community/tip-tech/how-manage-certificates-and-package-applications-different-ubuntu-setups/
Could you please try again using your certificate password instead of `tizen`?

echo `<PASSWORD>` | gnome-keyring-daemon --unlock

**Comment by JSUYA** [comment]
> And this building of application is done inside docker with ubuntu 22.04

https://developer.tizen.org/community/tip-tech/how-manage-certificates-and-package-applications-different-ubuntu-setups/
If you are using docker containers, you need to add the `--cap-add ipc_lock` option to the docker run command.

**Comment by adityapratap12** [comment]
step1> docker run -it -d --cap-add ipc_lock image_71c22fd907471476f2d368cb:1751 /bin/bash
step2>  dbus-run-session -- bash -c "echo {PASSWORD} | gnome-keyring-daemon --unlock && build.sh "


still getting same error :- error TS0005: Error occurred during tpk signing. Please check certificate file & password

**Comment by JSUYA** [comment]
Could you try again with `tizen` instead of `{PASSWORD}`? The reason I mentioned `{PASSWORD}` is because I didn't know it was a docker container environment. If the problem persists, I will ask the SDK team to resolve this issue.

step1> docker run -it -d --cap-add ipc_lock image_71c22fd907471476f2d368cb:1751 /bin/bash
step2> dbus-run-session -- bash -c "echo tizen | gnome-keyring-daemon --unlock && build.sh "

**Comment by swift-kim** [comment]
I had no problem building a C# flutter-tizen app in a Docker container. I referred to https://github.com/flutter-tizen/flutter-tizen/blob/master/.github/workflows/test.yml.

```sh
$ docker run -ti --rm ubuntu:22.04 bash
root@0f416cd3c89d:/# apt update && apt install -y curl file git make zip xz-utils

# Install Tizen Studio and required packages.
root@0f416cd3c89d:/# apt install -y libncurses5 python2.7 libpython2.7 gettext libkf5itemmodels5 libkf5kiowidgets5 libkchart2 dbus-x11 gnome-keyring
root@0f416cd3c89d:/# curl https://download.tizen.org/sdk/Installer/tizen-studio_6.0/web-cli_Tizen_Studio_6.0_ubuntu-64.bin -o install.bin
root@0f416cd3c89d:/# chmod a+x install.bin
root@0f416cd3c89d:/# adduser owner
root@0f416cd3c89d:/# su owner
owner@0f416cd3c89d:/$ ./install.bin --accept-license $HOME/tizen-studio
owner@0f416cd3c89d:/$ $HOME/tizen-studio/package-manager/package-manager-cli.bin install NativeToolchain-Gcc-9.2 IOT-Headed-6.0-NativeAppDevelopment-CLI
owner@0f416cd3c89d:/$ export PATH=$PATH:$HOME/tizen-studio/tools/ide/bin

# Create a certificate profile.
owner@0f416cd3c89d:/$ dbus-run-session -- bash -c "
          echo tizen | gnome-keyring-daemon --unlock &&
          tizen certificate -a tizen -p tizen -f tizen &&
          tizen security-profiles add \
            -n tizen \
            -a $HOME/tizen-studio-data/keystore/author/tizen.p12 \
            -p tizen
          "

# Install flutter-tizen.
owner@0f416cd3c89d:/$ cd ~
owner@0f416cd3c89d:~$ git clone https://github.com/flutter-tizen/flutter-tizen.git
owner@0f416cd3c89d:~$ export PATH=`pwd`/flutter-tizen/bin:$PATH

# Install .NET SDK.
owner@0f416cd3c89d:~$ curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
owner@0f416cd3c89d:~$ ./dotnet-install.sh --channel 9.0
owner@0f416cd3c89d:~$ export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools

# Create and build a project.
owner@0f416cd3c89d:~$ flutter-tizen create --tizen-language csharp dotnet_app
owner@0f416cd3c89d:~$ cd dotnet_app
owner@0f416cd3c89d:~/dotnet_app$ dbus-run-session -- bash -c "
          echo tizen | gnome-keyring-daemon --unlock &&
          flutter-tizen build tpk -pcommon --debug
          "
GNOME_KEYRING_CONTROL=/home/owner/.cache/keyring-GISG92
SSH_AUTH_SOCK=/home/owner/.cache/keyring-GISG92/ssh
The tizen profile is used for signing.
Building a Tizen application in debug mode...                       4.1s
✓ Built build/tizen/tpk/com.example.dotnet_app-1.0.0.tpk (31.2MB)
owner@0f416cd3c89d:~/dotnet_app$
```
